apiVersion: v1
entries:
  grafana-deployment:
  - apiVersion: v2
    appVersion: 9.2.10
    created: "2025-12-08T01:40:02.128672448Z"
    dependencies:
    - alias: grafana
      name: grafana
      repository: https://grafana.github.io/helm-charts
      version: 9.2.10
    - alias: telegraf
      name: telegraf
      repository: https://helm.influxdata.com/
      version: 1.8.60
    - alias: influxdb3
      name: influxdb3
      repository: https://srsran.github.io/srsRAN_Project_helm/
      version: 1.0.0
    description: Custom grafana-srsran chart packaged by Brandon B. Jozsa
    digest: 0f770df65fc8529f9081caa01432acad31355a3a9bd2146186b5a4903fc338aa
    name: grafana-deployment
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-grafana-srsran/grafana-deployment-1.3.0.tgz
    version: 1.3.0
  kubevirt-redfish:
  - apiVersion: v2
    appVersion: v0.2.3-f87ff92
    created: "2025-12-08T01:40:02.122487522Z"
    description: Custom kubevirt-redfish chart with enhanced features
    digest: 86ec4ca713c73c6576e83a079888fd553f036dd5459dd8cf21be97b667e60b99
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v2
    appVersion: v0.2.2-fee285c
    created: "2025-12-08T01:40:02.121618308Z"
    description: Custom kubevirt-redfish chart with enhanced features
    digest: f92a679f2429e94df4a1ab8297bc3d749a3f08d365d78d4eb158d032dbdf33ea
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: v0.2.1-fee285c1
    created: "2025-12-08T01:40:02.120774131Z"
    description: Custom kubevirt-redfish chart with enhanced features
    digest: 1fa72f48e13575ed80c5c13f1f4f1f2ff71721d1594a76427ddf83ec9a9fe6ee
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.1-fee285c1.tgz
    version: 0.2.1-fee285c1
  - apiVersion: v2
    appVersion: v0.2.1
    created: "2025-12-08T01:40:02.119874552Z"
    description: A Helm chart that provides a Redfish API server for KubeVirt VMs
    digest: a243ba0c35b589e0a20e2919b2dab65cf139fe84914de110d6e90817200342bf
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.1-73abb30.tgz
    version: 0.2.1-73abb30
  - apiVersion: v2
    appVersion: v0.2.0
    created: "2025-12-08T01:40:02.118964873Z"
    description: A Helm chart that provides a Redfish API server for KubeVirt VMs
    digest: 0e736215a0a05dafd5702e6093400c2d0050174d69477d5b664d048ee79de925
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.0.0-0.2.0-f310b659.tgz
    version: 0.0.0-0.2.0-f310b659
  ocp-on-cnv:
  - apiVersion: v2
    appVersion: v0.1.1-ac971ff
    created: "2025-12-08T01:40:02.124345427Z"
    description: 'Deprecated: VMs w/Fakefish for ZTP testing'
    digest: 857a87bf1c9ea714e6eb32056c720d0583566cc57ad6522b0db8ebfffa0c21ea
    name: ocp-on-cnv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/ocp-on-cnv/ocp-on-cnv-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: "1.0"
    created: "2025-12-08T01:40:02.123886375Z"
    description: This helm chart can be used to deploy OpenShift on top of OpenShift
      Virtualization using OpenShift's BMO and Fakefish.
    digest: aef476a611be690d3e86a45532ace9bd57fca4981cc0ee20df300efcfb5d65e8
    name: ocp-on-cnv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/ocp-on-cnv/ocp-on-cnv-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: v0.1.0-ac971ff
    created: "2025-12-08T01:40:02.122850565Z"
    description: 'Deprecated: VMs w/Fakefish for ZTP testing'
    digest: 7943b24d547a92c0209cda5293ed98a3d9aaadb26dc569003a01feba65527a45
    name: ocp-on-cnv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/ocp-on-cnv/ocp-on-cnv-0.1.0-devel.tgz
    version: 0.1.0-devel
  rt-tests:
  - apiVersion: v2
    appVersion: "2.8"
    created: "2025-12-08T01:40:02.129671402Z"
    description: Custom srsran-test chart packaged by Brandon B. Jozsa
    digest: 0c03dc202cc258013673459131d9bba3e5468547f6c47d9dc3fd7620695a116a
    home: https://wiki.linuxfoundation.org/realtime/documentation/howto/tools/rt-tests
    icon: https://wiki.linuxfoundation.org/_media/wiki/logo.png
    keywords:
    - rt-tests
    - srsran
    kubeVersion: '>= 1.16.0-0'
    name: rt-tests
    sources:
    - https://web.git.kernel.org/pub/scm/utils/rt-tests/rt-tests.git/
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-rt-tests/rt-tests-1.0.0.tgz
    version: 1.0.0
  ru-emulator:
  - apiVersion: v2
    appVersion: 2024.10.0
    created: "2025-12-08T01:40:02.130028415Z"
    description: Custom srsran-emulator chart packaged by Brandon B. Jozsa
    digest: b76c0519f633f11f6a71dc15b75ffe0883bc281947c6ad8230b0ee909e0a767a
    name: ru-emulator
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-ru-emulator/ru-emulator-1.1.0.tgz
    version: 1.1.0
  srsran-cu-du:
  - apiVersion: v2
    appVersion: "25.04"
    created: "2025-12-08T01:40:02.129361848Z"
    description: Custom srsran-project chart packaged by Brandon B. Jozsa
    digest: f929e41ebac8b59d8e4086c2a7564c427c1c680d13058cac0c06371339dbe550
    home: https://docs.srsran.com/projects/project/en/latest/
    icon: https://docs.srsran.com/en/latest/_static/logo.png
    keywords:
    - srsran
    - 5g
    - oran
    - vran
    - gnb
    - mobile
    kubeVersion: '>= 1.24.0-0'
    name: srsran-cu-du
    sources:
    - https://github.com/srsran/srsran_project
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-project/srsran-cu-du-2.3.1.tgz
    version: 2.3.1
  tuned:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-12-08T01:40:02.130307533Z"
    description: Custom srsran-tuned chart packaged by Brandon B. Jozsa
    digest: d31ff0928b8013327f9126f1529eae63e401a2e161b2256d93990ac38b2bcdfc
    name: tuned
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-tuned/tuned-0.5.0.tgz
    version: 0.5.0
  vms-on-ocpv:
  - apiVersion: v2
    appVersion: v0.1.1-ff18cb3
    created: "2025-12-08T01:40:02.130918948Z"
    description: Simple OpenShift Virtualization chart, typically used for kubevirt-redfish
      testing
    digest: 1465762391acf6c2db10bc27ced2c72deb5d37bb7f874d1fd2bb966b584160a3
    home: https://github.com/v1k0d3n/vms-on-ocpv
    keywords:
    - kubevirt
    - virtualization
    - vm
    - openshift
    maintainers:
    - email: v1k0d3n@example.com
      name: v1k0d3n
    name: vms-on-ocpv
    sources:
    - https://github.com/v1k0d3n/vms-on-ocpv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/vms-on-ocpv/vms-on-ocpv-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: v0.1.0-ff18cb3
    created: "2025-12-08T01:40:02.130630713Z"
    description: Simple OpenShift Virtualization chart, typically used for kubevirt-redfish
      testing
    digest: ffa58bbbb5c0bed7cc7d92337035c1f0bdeb6d5d8a9e3cdfa9207edd44609bf2
    home: https://github.com/v1k0d3n/vms-on-ocpv
    keywords:
    - kubevirt
    - virtualization
    - vm
    - openshift
    maintainers:
    - email: v1k0d3n@example.com
      name: v1k0d3n
    name: vms-on-ocpv
    sources:
    - https://github.com/v1k0d3n/vms-on-ocpv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/vms-on-ocpv/vms-on-ocpv-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-08T01:40:02.117786356Z"
