apiVersion: v1
entries:
  grafana-deployment:
  - apiVersion: v2
    appVersion: 9.2.10
    created: "2025-12-08T01:57:25.012405799Z"
    dependencies:
    - alias: grafana
      name: grafana
      repository: https://grafana.github.io/helm-charts
      version: 9.2.10
    - alias: telegraf
      name: telegraf
      repository: https://helm.influxdata.com/
      version: 1.8.60
    - alias: influxdb3
      name: influxdb3
      repository: https://srsran.github.io/srsRAN_Project_helm/
      version: 1.0.0
    description: Custom grafana-srsran chart packaged by Brandon B. Jozsa
    digest: 767914aa663293c995d418fee9e082676ff823a50fcc0532a683d01b876a3323
    name: grafana-deployment
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-grafana-srsran/grafana-deployment-1.3.0.tgz
    version: 1.3.0
  influxdb3:
  - apiVersion: v2
    appVersion: 3.1.0-core
    created: "2025-12-08T01:57:25.012701851Z"
    description: Custom srsran-influxdb chart packaged by Brandon B. Jozsa
    digest: 5106313a84b6e0b4038582554a879d4a192e1b3ecdbd33ad4498cd26fe4e984d
    name: influxdb3
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-influxdb3/influxdb3-1.0.0.tgz
    version: 1.0.0
  kubevirt-redfish:
  - apiVersion: v2
    appVersion: v0.2.3-f87ff92
    created: "2025-12-08T01:57:25.005234575Z"
    description: Custom kubevirt-redfish chart with enhanced features
    digest: eaf8a924d2ba31a5f03136107e2ba64f214306b97ca89f40c7f728ef69e34074
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v2
    appVersion: v0.2.2-fee285c
    created: "2025-12-08T01:57:25.004295196Z"
    description: Custom kubevirt-redfish chart with enhanced features
    digest: f92a679f2429e94df4a1ab8297bc3d749a3f08d365d78d4eb158d032dbdf33ea
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: v0.2.1-fee285c1
    created: "2025-12-08T01:57:25.00342712Z"
    description: Custom kubevirt-redfish chart with enhanced features
    digest: 1fa72f48e13575ed80c5c13f1f4f1f2ff71721d1594a76427ddf83ec9a9fe6ee
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.1-fee285c1.tgz
    version: 0.2.1-fee285c1
  - apiVersion: v2
    appVersion: v0.2.1
    created: "2025-12-08T01:57:25.002507439Z"
    description: A Helm chart that provides a Redfish API server for KubeVirt VMs
    digest: a243ba0c35b589e0a20e2919b2dab65cf139fe84914de110d6e90817200342bf
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.1-73abb30.tgz
    version: 0.2.1-73abb30
  - apiVersion: v2
    appVersion: v0.2.0
    created: "2025-12-08T01:57:25.001563842Z"
    description: A Helm chart that provides a Redfish API server for KubeVirt VMs
    digest: 0e736215a0a05dafd5702e6093400c2d0050174d69477d5b664d048ee79de925
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.0.0-0.2.0-f310b659.tgz
    version: 0.0.0-0.2.0-f310b659
  linuxptp:
  - apiVersion: v2
    appVersion: 4.4.0
    created: "2025-12-08T01:57:25.013291218Z"
    description: Custom srsran-ptp chart packaged by Brandon B. Jozsa
    digest: 70cae62265ea17d0fcf9e806a542a8e868134d901bd756af3c77500f80790a11
    home: https://linuxptp.nwtime.org/
    icon: https://linuxptp.nwtime.org/images/logo.png
    keywords:
    - linuxptp
    - ptp4l
    - phc2sys
    - ptp
    - srsran
    kubeVersion: '>= 1.24.0-0'
    name: linuxptp
    sources:
    - https://github.com/richardcochran/linuxptp
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-linuxptp/linuxptp-1.3.1.tgz
    version: 1.3.1
  metrics-server:
  - apiVersion: v2
    appVersion: 2024.10.0
    created: "2025-12-08T01:57:25.013585876Z"
    description: Custom srsran-metrics-server chart packaged by Brandon B. Jozsa
    digest: d154b1c432154db4886027d816f916214b08712cf9be96f992b504ed0e12f4c4
    name: metrics-server
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-metrics-server/metrics-server-1.2.0.tgz
    version: 1.2.0
  ocp-on-cnv:
  - apiVersion: v2
    appVersion: v0.1.1-ac971ff
    created: "2025-12-08T01:57:25.006340213Z"
    description: 'Deprecated: VMs w/Fakefish for ZTP testing'
    digest: 950c0006bf65807c2fc079eed4423cf7ff0427e32baf5cf0c15bd2973ab79f15
    name: ocp-on-cnv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/ocp-on-cnv/ocp-on-cnv-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: "1.0"
    created: "2025-12-08T01:57:25.005990031Z"
    description: This helm chart can be used to deploy OpenShift on top of OpenShift
      Virtualization using OpenShift's BMO and Fakefish.
    digest: aef476a611be690d3e86a45532ace9bd57fca4981cc0ee20df300efcfb5d65e8
    name: ocp-on-cnv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/ocp-on-cnv/ocp-on-cnv-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: v0.1.0-ac971ff
    created: "2025-12-08T01:57:25.005625803Z"
    description: 'Deprecated: VMs w/Fakefish for ZTP testing'
    digest: 7943b24d547a92c0209cda5293ed98a3d9aaadb26dc569003a01feba65527a45
    name: ocp-on-cnv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/ocp-on-cnv/ocp-on-cnv-0.1.0-devel.tgz
    version: 0.1.0-devel
  onap-smo-lite:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-12-08T01:57:25.014782203Z"
    description: Custom srsran onap-smo-lite chart packaged by Brandon B. Jozsa
    digest: 98a26470f16c0c0de7ce952ebbcd153f5df8b899bc4b19043ad67f3f5bc53f7b
    name: onap-smo-lite
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-onap-smo-lite/onap-smo-lite-0.3.0.tgz
    version: 0.3.0
  rt-tests:
  - apiVersion: v2
    appVersion: "2.8"
    created: "2025-12-08T01:57:25.015786322Z"
    description: Custom srsran-test chart packaged by Brandon B. Jozsa
    digest: 4db62b58c1bd8d8bfb77bc46c459eb1ef8ccb3fe6f5b2f0819d33375dc9821ba
    home: https://wiki.linuxfoundation.org/realtime/documentation/howto/tools/rt-tests
    icon: https://wiki.linuxfoundation.org/_media/wiki/logo.png
    keywords:
    - rt-tests
    - srsran
    kubeVersion: '>= 1.16.0-0'
    name: rt-tests
    sources:
    - https://web.git.kernel.org/pub/scm/utils/rt-tests/rt-tests.git/
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-rt-tests/rt-tests-1.0.0.tgz
    version: 1.0.0
  ru-emulator:
  - apiVersion: v2
    appVersion: 2024.10.0
    created: "2025-12-08T01:57:25.016135051Z"
    description: Custom srsran-emulator chart packaged by Brandon B. Jozsa
    digest: 457dc39f7f22efe49c8078226203d75aa40d74cafc55c15f9b505c89c25cd208
    name: ru-emulator
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-ru-emulator/ru-emulator-1.1.0.tgz
    version: 1.1.0
  srsran-cu-du:
  - apiVersion: v2
    appVersion: "25.04"
    created: "2025-12-08T01:57:25.015499108Z"
    description: Custom srsran-project chart packaged by Brandon B. Jozsa
    digest: 2437942c0657058a253cf5bb29c43440d874eeb187e30138b615a50e0fe71c0d
    home: https://docs.srsran.com/projects/project/en/latest/
    icon: https://docs.srsran.com/en/latest/_static/logo.png
    keywords:
    - srsran
    - 5g
    - oran
    - vran
    - gnb
    - mobile
    kubeVersion: '>= 1.24.0-0'
    name: srsran-cu-du
    sources:
    - https://github.com/srsran/srsran_project
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-project/srsran-cu-du-2.3.1.tgz
    version: 2.3.1
  tuned:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-12-08T01:57:25.016399593Z"
    description: Custom srsran-tuned chart packaged by Brandon B. Jozsa
    digest: eaff515650617a6387ed2e37b9e71bd0658d34d62aeae8dd65a2e9197851855c
    name: tuned
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-tuned/tuned-0.5.0.tgz
    version: 0.5.0
  vms-on-ocpv:
  - apiVersion: v2
    appVersion: v0.1.1-ff18cb3
    created: "2025-12-08T01:57:25.016987307Z"
    description: Simple OpenShift Virtualization chart, typically used for kubevirt-redfish
      testing
    digest: 73cd39f6b10eb0e14b295ba7d1e022a4b88003487021c8415af3cca6914bb1ed
    home: https://github.com/v1k0d3n/vms-on-ocpv
    keywords:
    - kubevirt
    - virtualization
    - vm
    - openshift
    maintainers:
    - email: v1k0d3n@example.com
      name: v1k0d3n
    name: vms-on-ocpv
    sources:
    - https://github.com/v1k0d3n/vms-on-ocpv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/vms-on-ocpv/vms-on-ocpv-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: v0.1.0-ff18cb3
    created: "2025-12-08T01:57:25.016704581Z"
    description: Simple OpenShift Virtualization chart, typically used for kubevirt-redfish
      testing
    digest: ffa58bbbb5c0bed7cc7d92337035c1f0bdeb6d5d8a9e3cdfa9207edd44609bf2
    home: https://github.com/v1k0d3n/vms-on-ocpv
    keywords:
    - kubevirt
    - virtualization
    - vm
    - openshift
    maintainers:
    - email: v1k0d3n@example.com
      name: v1k0d3n
    name: vms-on-ocpv
    sources:
    - https://github.com/v1k0d3n/vms-on-ocpv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/vms-on-ocpv/vms-on-ocpv-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-08T01:57:25.000332319Z"
