apiVersion: v1
entries:
  kubevirt-redfish:
  - apiVersion: v2
    appVersion: v0.2.3-f87ff92
    created: "2025-11-30T02:43:44.945639832Z"
    description: Custom kubevirt-redfish chart with enhanced features
    digest: 3036f81001bc82e18a7e0f085f5153be1adcab3ac166bc45e3d87f67aabbf01d
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v2
    appVersion: v0.2.2-fee285c
    created: "2025-11-30T02:43:44.944725613Z"
    description: Custom kubevirt-redfish chart with enhanced features
    digest: f92a679f2429e94df4a1ab8297bc3d749a3f08d365d78d4eb158d032dbdf33ea
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: v0.2.1-fee285c1
    created: "2025-11-30T02:43:44.943865344Z"
    description: Custom kubevirt-redfish chart with enhanced features
    digest: 1fa72f48e13575ed80c5c13f1f4f1f2ff71721d1594a76427ddf83ec9a9fe6ee
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.1-fee285c1.tgz
    version: 0.2.1-fee285c1
  - apiVersion: v2
    appVersion: v0.2.1
    created: "2025-11-30T02:43:44.942950233Z"
    description: A Helm chart that provides a Redfish API server for KubeVirt VMs
    digest: a243ba0c35b589e0a20e2919b2dab65cf139fe84914de110d6e90817200342bf
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.1-73abb30.tgz
    version: 0.2.1-73abb30
  - apiVersion: v2
    appVersion: v0.2.0
    created: "2025-11-30T02:43:44.942023269Z"
    description: A Helm chart that provides a Redfish API server for KubeVirt VMs
    digest: 0e736215a0a05dafd5702e6093400c2d0050174d69477d5b664d048ee79de925
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.0.0-0.2.0-f310b659.tgz
    version: 0.0.0-0.2.0-f310b659
  ocp-on-cnv:
  - apiVersion: v2
    appVersion: v0.1.1-ac971ff
    created: "2025-11-30T02:43:44.946774144Z"
    description: 'Deprecated: VMs w/Fakefish for ZTP testing'
    digest: 2c273d38959327cffc00900807086e227b1ca9fe260fde0c61b7f7fca2978372
    name: ocp-on-cnv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/ocp-on-cnv/ocp-on-cnv-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: "1.0"
    created: "2025-11-30T02:43:44.946402579Z"
    description: This helm chart can be used to deploy OpenShift on top of OpenShift
      Virtualization using OpenShift's BMO and Fakefish.
    digest: aef476a611be690d3e86a45532ace9bd57fca4981cc0ee20df300efcfb5d65e8
    name: ocp-on-cnv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/ocp-on-cnv/ocp-on-cnv-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: v0.1.0-ac971ff
    created: "2025-11-30T02:43:44.946022939Z"
    description: 'Deprecated: VMs w/Fakefish for ZTP testing'
    digest: 7943b24d547a92c0209cda5293ed98a3d9aaadb26dc569003a01feba65527a45
    name: ocp-on-cnv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/ocp-on-cnv/ocp-on-cnv-0.1.0-devel.tgz
    version: 0.1.0-devel
  vms-on-ocpv:
  - apiVersion: v2
    appVersion: v0.1.1-ff18cb3
    created: "2025-11-30T02:43:44.947863741Z"
    description: Simple OpenShift Virtualization chart, typically used for kubevirt-redfish
      testing
    digest: 5819d36a1d0582aaca700bc8110e4db3ce2c4f25239133666425f1ece7171097
    home: https://github.com/v1k0d3n/vms-on-ocpv
    keywords:
    - kubevirt
    - virtualization
    - vm
    - openshift
    maintainers:
    - email: v1k0d3n@example.com
      name: v1k0d3n
    name: vms-on-ocpv
    sources:
    - https://github.com/v1k0d3n/vms-on-ocpv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/vms-on-ocpv/vms-on-ocpv-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: v0.1.0-ff18cb3
    created: "2025-11-30T02:43:44.947069917Z"
    description: Simple OpenShift Virtualization chart, typically used for kubevirt-redfish
      testing
    digest: ffa58bbbb5c0bed7cc7d92337035c1f0bdeb6d5d8a9e3cdfa9207edd44609bf2
    home: https://github.com/v1k0d3n/vms-on-ocpv
    keywords:
    - kubevirt
    - virtualization
    - vm
    - openshift
    maintainers:
    - email: v1k0d3n@example.com
      name: v1k0d3n
    name: vms-on-ocpv
    sources:
    - https://github.com/v1k0d3n/vms-on-ocpv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/vms-on-ocpv/vms-on-ocpv-0.1.0.tgz
    version: 0.1.0
generated: "2025-11-30T02:43:44.940801996Z"
