apiVersion: v1
entries:
  grafana:
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/grafana/helm-charts
        - name: Upstream Project
          url: https://github.com/grafana/grafana
    apiVersion: v2
    appVersion: 12.0.2
    created: "2025-12-21T02:45:41.007510232Z"
    description: Custom grafana-srsran chart packaged by Brandon B. Jozsa
    digest: acdf546c2f32d8b40c1cdaa10e959bb1386f54904e25aee59ac7543819540581
    home: https://grafana.com
    icon: https://artifacthub.io/image/b4fed1a7-6c8f-4945-b99d-096efa3e4116
    keywords:
    - monitoring
    - metric
    kubeVersion: ^1.8.0-0
    maintainers:
    - email: zanhsieh@gmail.com
      name: zanhsieh
    - email: rluckie@cisco.com
      name: rtluckie
    - email: maor.friedman@redhat.com
      name: maorfr
    - email: miroslav.hadzhiev@gmail.com
      name: Xtigyro
    - email: mail@torstenwalter.de
      name: torstenwalter
    - email: github@jkroepke.de
      name: jkroepke
    name: grafana
    sources:
    - https://github.com/grafana/grafana
    - https://github.com/grafana/helm-charts
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-grafana/grafana-9.2.10.tgz
    version: 9.2.10
  grafana-deployment:
  - apiVersion: v2
    appVersion: 9.2.10
    created: "2025-12-21T02:45:41.012531709Z"
    dependencies:
    - alias: grafana
      name: grafana
      repository: https://grafana.github.io/helm-charts
      version: 9.2.10
    - alias: telegraf
      name: telegraf
      repository: https://helm.influxdata.com/
      version: 1.8.60
    - alias: influxdb3
      name: influxdb3
      repository: https://srsran.github.io/srsRAN_Project_helm/
      version: 1.0.0
    description: Custom grafana-srsran chart packaged by Brandon B. Jozsa
    digest: 163b2a4d98856a7aff520aac34fc5697d3bdfea42a2233521cb00064ff20dbde
    name: grafana-deployment
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-grafana-srsran/grafana-deployment-1.3.0.tgz
    version: 1.3.0
  influxdb3:
  - apiVersion: v2
    appVersion: 3.1.0-core
    created: "2025-12-21T02:45:41.012830211Z"
    description: Custom srsran-influxdb chart packaged by Brandon B. Jozsa
    digest: b85adda2f1880e4fee03e18d01dd12277558d18f04ac25cacaad302ce6d3d16d
    name: influxdb3
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-influxdb3/influxdb3-1.0.0.tgz
    version: 1.0.0
  kubevirt-redfish:
  - apiVersion: v2
    appVersion: v0.2.3-f87ff92
    created: "2025-12-21T02:45:41.003407327Z"
    description: Custom kubevirt-redfish chart with enhanced features
    digest: 357260141dce22ed1a1ac05cb7fb9f4801e59ec210363e7e982b67f9ad9b0918
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v2
    appVersion: v0.2.2-fee285c
    created: "2025-12-21T02:45:41.002512753Z"
    description: Custom kubevirt-redfish chart with enhanced features
    digest: f92a679f2429e94df4a1ab8297bc3d749a3f08d365d78d4eb158d032dbdf33ea
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: v0.2.1-fee285c1
    created: "2025-12-21T02:45:41.001580978Z"
    description: Custom kubevirt-redfish chart with enhanced features
    digest: 1fa72f48e13575ed80c5c13f1f4f1f2ff71721d1594a76427ddf83ec9a9fe6ee
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.1-fee285c1.tgz
    version: 0.2.1-fee285c1
  - apiVersion: v2
    appVersion: v0.2.1
    created: "2025-12-21T02:45:40.999931044Z"
    description: A Helm chart that provides a Redfish API server for KubeVirt VMs
    digest: a243ba0c35b589e0a20e2919b2dab65cf139fe84914de110d6e90817200342bf
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.1-73abb30.tgz
    version: 0.2.1-73abb30
  - apiVersion: v2
    appVersion: v0.2.0
    created: "2025-12-21T02:45:40.999049514Z"
    description: A Helm chart that provides a Redfish API server for KubeVirt VMs
    digest: 0e736215a0a05dafd5702e6093400c2d0050174d69477d5b664d048ee79de925
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.0.0-0.2.0-f310b659.tgz
    version: 0.0.0-0.2.0-f310b659
  linuxptp:
  - apiVersion: v2
    appVersion: 4.4.0
    created: "2025-12-21T02:45:41.013416585Z"
    description: Custom srsran-ptp chart packaged by Brandon B. Jozsa
    digest: 1ee50b05cb51cd9959ab88ce8961ce8ef838512bf3f0c4840e3322e5dbbfb9e4
    home: https://linuxptp.nwtime.org/
    icon: https://linuxptp.nwtime.org/images/logo.png
    keywords:
    - linuxptp
    - ptp4l
    - phc2sys
    - ptp
    - srsran
    kubeVersion: '>= 1.24.0-0'
    name: linuxptp
    sources:
    - https://github.com/richardcochran/linuxptp
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-linuxptp/linuxptp-1.3.1.tgz
    version: 1.3.1
  metrics-server:
  - apiVersion: v2
    appVersion: 2024.10.0
    created: "2025-12-21T02:45:41.013759571Z"
    description: Custom srsran-metrics-server chart packaged by Brandon B. Jozsa
    digest: 20a93f4855f30872d509b2303e4cf2965ced438a8cf444badcce6bb8fc65d4aa
    name: metrics-server
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-metrics-server/metrics-server-1.2.0.tgz
    version: 1.2.0
  ocp-on-cnv:
  - apiVersion: v2
    appVersion: v0.1.1-ac971ff
    created: "2025-12-21T02:45:41.004614801Z"
    description: 'Deprecated: VMs w/Fakefish for ZTP testing'
    digest: c5b39c3e3478e9aad27ecf76071fe4c962f9c0ea2f669d901747500895c5f243
    name: ocp-on-cnv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/ocp-on-cnv/ocp-on-cnv-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: "1.0"
    created: "2025-12-21T02:45:41.004260854Z"
    description: This helm chart can be used to deploy OpenShift on top of OpenShift
      Virtualization using OpenShift's BMO and Fakefish.
    digest: aef476a611be690d3e86a45532ace9bd57fca4981cc0ee20df300efcfb5d65e8
    name: ocp-on-cnv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/ocp-on-cnv/ocp-on-cnv-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: v0.1.0-ac971ff
    created: "2025-12-21T02:45:41.003896138Z"
    description: 'Deprecated: VMs w/Fakefish for ZTP testing'
    digest: 7943b24d547a92c0209cda5293ed98a3d9aaadb26dc569003a01feba65527a45
    name: ocp-on-cnv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/ocp-on-cnv/ocp-on-cnv-0.1.0-devel.tgz
    version: 0.1.0-devel
  onap-smo-lite:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-12-21T02:45:41.014958959Z"
    description: Custom srsran onap-smo-lite chart packaged by Brandon B. Jozsa
    digest: 60099bc378077ea3258b19be60b4991126a431c3388c155194b58c1441b5cc87
    name: onap-smo-lite
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-onap-smo-lite/onap-smo-lite-0.3.0.tgz
    version: 0.3.0
  rt-tests:
  - apiVersion: v2
    appVersion: "2.8"
    created: "2025-12-21T02:45:41.01595267Z"
    description: Custom srsran-test chart packaged by Brandon B. Jozsa
    digest: 31a50241e3db2030c60d0cceb8ae6cfbb7485021ade5563fba8788b1288cd625
    home: https://wiki.linuxfoundation.org/realtime/documentation/howto/tools/rt-tests
    icon: https://wiki.linuxfoundation.org/_media/wiki/logo.png
    keywords:
    - rt-tests
    - srsran
    kubeVersion: '>= 1.16.0-0'
    name: rt-tests
    sources:
    - https://web.git.kernel.org/pub/scm/utils/rt-tests/rt-tests.git/
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-rt-tests/rt-tests-1.0.0.tgz
    version: 1.0.0
  ru-emulator:
  - apiVersion: v2
    appVersion: 2024.10.0
    created: "2025-12-21T02:45:41.016280507Z"
    description: Custom srsran-emulator chart packaged by Brandon B. Jozsa
    digest: 5fda4a5583f8e9d6515ef390021b24c9087f0faf163d995e73c065af4e0c24fa
    name: ru-emulator
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-ru-emulator/ru-emulator-1.1.0.tgz
    version: 1.1.0
  srsran-cu-du:
  - apiVersion: v2
    appVersion: "25.04"
    created: "2025-12-21T02:45:41.015640943Z"
    description: Custom srsran-project chart packaged by Brandon B. Jozsa
    digest: c89e69d23ccd50e78fbe5669df995177c5f27e60644feec52b1ecdeaf1c861e0
    home: https://docs.srsran.com/projects/project/en/latest/
    icon: https://docs.srsran.com/en/latest/_static/logo.png
    keywords:
    - srsran
    - 5g
    - oran
    - vran
    - gnb
    - mobile
    kubeVersion: '>= 1.24.0-0'
    name: srsran-cu-du
    sources:
    - https://github.com/srsran/srsran_project
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-project/srsran-cu-du-2.3.1.tgz
    version: 2.3.1
  tuned:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-12-21T02:45:41.016539345Z"
    description: Custom srsran-tuned chart packaged by Brandon B. Jozsa
    digest: 3b732b35ad3ac75dd1b551e80a9d13a3ba00bf61ae552612975b97ed3cee4b97
    name: tuned
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-tuned/tuned-0.5.0.tgz
    version: 0.5.0
  vms-on-ocpv:
  - apiVersion: v2
    appVersion: v0.1.1-ff18cb3
    created: "2025-12-21T02:45:41.017121711Z"
    description: Simple OpenShift Virtualization chart, typically used for kubevirt-redfish
      testing
    digest: ef34362710e5cde3e2261345e84766b23acf7d5a5d9d9d38a75094765596e7ec
    home: https://github.com/v1k0d3n/vms-on-ocpv
    keywords:
    - kubevirt
    - virtualization
    - vm
    - openshift
    maintainers:
    - email: v1k0d3n@example.com
      name: v1k0d3n
    name: vms-on-ocpv
    sources:
    - https://github.com/v1k0d3n/vms-on-ocpv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/vms-on-ocpv/vms-on-ocpv-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: v0.1.0-ff18cb3
    created: "2025-12-21T02:45:41.01684515Z"
    description: Simple OpenShift Virtualization chart, typically used for kubevirt-redfish
      testing
    digest: ffa58bbbb5c0bed7cc7d92337035c1f0bdeb6d5d8a9e3cdfa9207edd44609bf2
    home: https://github.com/v1k0d3n/vms-on-ocpv
    keywords:
    - kubevirt
    - virtualization
    - vm
    - openshift
    maintainers:
    - email: v1k0d3n@example.com
      name: v1k0d3n
    name: vms-on-ocpv
    sources:
    - https://github.com/v1k0d3n/vms-on-ocpv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/vms-on-ocpv/vms-on-ocpv-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-21T02:45:40.997935085Z"
