apiVersion: v1
entries:
  grafana:
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/grafana/helm-charts
        - name: Upstream Project
          url: https://github.com/grafana/grafana
    apiVersion: v2
    appVersion: 12.0.2
    created: "2026-01-04T02:52:32.105354339Z"
    description: Custom grafana-srsran chart packaged by Brandon B. Jozsa
    digest: a307d0102059ed4f87a5d22ee01791c30338b8f6d2bbfe4b3b618fb1b4acf877
    home: https://grafana.com
    icon: https://artifacthub.io/image/b4fed1a7-6c8f-4945-b99d-096efa3e4116
    keywords:
    - monitoring
    - metric
    kubeVersion: ^1.8.0-0
    maintainers:
    - email: zanhsieh@gmail.com
      name: zanhsieh
    - email: rluckie@cisco.com
      name: rtluckie
    - email: maor.friedman@redhat.com
      name: maorfr
    - email: miroslav.hadzhiev@gmail.com
      name: Xtigyro
    - email: mail@torstenwalter.de
      name: torstenwalter
    - email: github@jkroepke.de
      name: jkroepke
    name: grafana
    sources:
    - https://github.com/grafana/grafana
    - https://github.com/grafana/helm-charts
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-grafana/grafana-9.2.10.tgz
    version: 9.2.10
  grafana-deployment:
  - apiVersion: v2
    appVersion: 9.2.10
    created: "2026-01-04T02:52:32.109828454Z"
    dependencies:
    - alias: grafana
      name: grafana
      repository: https://grafana.github.io/helm-charts
      version: 9.2.10
    - alias: telegraf
      name: telegraf
      repository: https://helm.influxdata.com/
      version: 1.8.60
    - alias: influxdb3
      name: influxdb3
      repository: https://srsran.github.io/srsRAN_Project_helm/
      version: 1.0.0
    description: Custom grafana-srsran chart packaged by Brandon B. Jozsa
    digest: b2ff767543befe78cdca6d5de519ec8cb45a0b713a44804f57f209a94c32e488
    name: grafana-deployment
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-grafana-srsran/grafana-deployment-1.3.0.tgz
    version: 1.3.0
  influxdb3:
  - apiVersion: v2
    appVersion: 3.1.0-core
    created: "2026-01-04T02:52:32.110082084Z"
    description: Custom srsran-influxdb chart packaged by Brandon B. Jozsa
    digest: b934a6227097493f9b772e357146542e238eb4d7924fbadf818031bc7086a2ae
    name: influxdb3
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-influxdb3/influxdb3-1.0.0.tgz
    version: 1.0.0
  kubevirt-redfish:
  - apiVersion: v2
    appVersion: v0.2.3-f87ff92
    created: "2026-01-04T02:52:32.100530725Z"
    description: Custom kubevirt-redfish chart with enhanced features
    digest: 7c296b12c37ef60f93f5fdf9d67ac6cbac918bdb3bf4ac5836218fd9aa2702be
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v2
    appVersion: v0.2.2-fee285c
    created: "2026-01-04T02:52:32.099664689Z"
    description: Custom kubevirt-redfish chart with enhanced features
    digest: f92a679f2429e94df4a1ab8297bc3d749a3f08d365d78d4eb158d032dbdf33ea
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: v0.2.1-fee285c1
    created: "2026-01-04T02:52:32.098820064Z"
    description: Custom kubevirt-redfish chart with enhanced features
    digest: 1fa72f48e13575ed80c5c13f1f4f1f2ff71721d1594a76427ddf83ec9a9fe6ee
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.1-fee285c1.tgz
    version: 0.2.1-fee285c1
  - apiVersion: v2
    appVersion: v0.2.1
    created: "2026-01-04T02:52:32.097934608Z"
    description: A Helm chart that provides a Redfish API server for KubeVirt VMs
    digest: a243ba0c35b589e0a20e2919b2dab65cf139fe84914de110d6e90817200342bf
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.1-73abb30.tgz
    version: 0.2.1-73abb30
  - apiVersion: v2
    appVersion: v0.2.0
    created: "2026-01-04T02:52:32.097004524Z"
    description: A Helm chart that provides a Redfish API server for KubeVirt VMs
    digest: 0e736215a0a05dafd5702e6093400c2d0050174d69477d5b664d048ee79de925
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.0.0-0.2.0-f310b659.tgz
    version: 0.0.0-0.2.0-f310b659
  linuxptp:
  - apiVersion: v2
    appVersion: 4.4.0
    created: "2026-01-04T02:52:32.110646744Z"
    description: Custom srsran-ptp chart packaged by Brandon B. Jozsa
    digest: eb88713e6be09cb051d143fa0f8473657f47a9074ffb0c88318ff3cf83d42fc6
    home: https://linuxptp.nwtime.org/
    icon: https://linuxptp.nwtime.org/images/logo.png
    keywords:
    - linuxptp
    - ptp4l
    - phc2sys
    - ptp
    - srsran
    kubeVersion: '>= 1.24.0-0'
    name: linuxptp
    sources:
    - https://github.com/richardcochran/linuxptp
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-linuxptp/linuxptp-1.3.1.tgz
    version: 1.3.1
  metrics-server:
  - apiVersion: v2
    appVersion: 2024.10.0
    created: "2026-01-04T02:52:32.110897478Z"
    description: Custom srsran-metrics-server chart packaged by Brandon B. Jozsa
    digest: 7be10f2993596742d14f0f5787ca09588c4f027e4ef956d2caa257bbd12ad047
    name: metrics-server
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-metrics-server/metrics-server-1.2.0.tgz
    version: 1.2.0
  ocp-on-cnv:
  - apiVersion: v2
    appVersion: v0.1.1-ac971ff
    created: "2026-01-04T02:52:32.101762227Z"
    description: 'Deprecated: VMs w/Fakefish for ZTP testing'
    digest: 60d08063f19f0ac9eb53e26f8b9cfad62a9c06f76b0b40a41576910a5e8be554
    name: ocp-on-cnv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/ocp-on-cnv/ocp-on-cnv-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: "1.0"
    created: "2026-01-04T02:52:32.101429702Z"
    description: This helm chart can be used to deploy OpenShift on top of OpenShift
      Virtualization using OpenShift's BMO and Fakefish.
    digest: aef476a611be690d3e86a45532ace9bd57fca4981cc0ee20df300efcfb5d65e8
    name: ocp-on-cnv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/ocp-on-cnv/ocp-on-cnv-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: v0.1.0-ac971ff
    created: "2026-01-04T02:52:32.100878372Z"
    description: 'Deprecated: VMs w/Fakefish for ZTP testing'
    digest: 7943b24d547a92c0209cda5293ed98a3d9aaadb26dc569003a01feba65527a45
    name: ocp-on-cnv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/ocp-on-cnv/ocp-on-cnv-0.1.0-devel.tgz
    version: 0.1.0-devel
  onap-smo-lite:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-01-04T02:52:32.112334076Z"
    description: Custom srsran onap-smo-lite chart packaged by Brandon B. Jozsa
    digest: 08fdaccd867c63c4d7058966bc5cbb32d29716b7f5479493d93522fe6e7a3c28
    name: onap-smo-lite
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-onap-smo-lite/onap-smo-lite-0.3.0.tgz
    version: 0.3.0
  rt-tests:
  - apiVersion: v2
    appVersion: "2.8"
    created: "2026-01-04T02:52:32.11384138Z"
    description: Custom srsran-test chart packaged by Brandon B. Jozsa
    digest: 30bd09b849b8ce4a61aa1ab314d46679eb9cd8004ccad0859712f421f8c84b99
    home: https://wiki.linuxfoundation.org/realtime/documentation/howto/tools/rt-tests
    icon: https://wiki.linuxfoundation.org/_media/wiki/logo.png
    keywords:
    - rt-tests
    - srsran
    kubeVersion: '>= 1.16.0-0'
    name: rt-tests
    sources:
    - https://web.git.kernel.org/pub/scm/utils/rt-tests/rt-tests.git/
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-rt-tests/rt-tests-1.0.0.tgz
    version: 1.0.0
  ru-emulator:
  - apiVersion: v2
    appVersion: 2024.10.0
    created: "2026-01-04T02:52:32.114153035Z"
    description: Custom srsran-emulator chart packaged by Brandon B. Jozsa
    digest: f6c6f653cd8c7baebb067e2f89f4db66fc37f986bba511e380b09d813543cedb
    name: ru-emulator
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-ru-emulator/ru-emulator-1.1.0.tgz
    version: 1.1.0
  srsran-cu-du:
  - apiVersion: v2
    appVersion: "25.04"
    created: "2026-01-04T02:52:32.113547008Z"
    description: Custom srsran-project chart packaged by Brandon B. Jozsa
    digest: 6da25ec626b75310f8d5485f5abf3600b4070d6a78ace395d55e24676fa11951
    home: https://docs.srsran.com/projects/project/en/latest/
    icon: https://docs.srsran.com/en/latest/_static/logo.png
    keywords:
    - srsran
    - 5g
    - oran
    - vran
    - gnb
    - mobile
    kubeVersion: '>= 1.24.0-0'
    name: srsran-cu-du
    sources:
    - https://github.com/srsran/srsran_project
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-project/srsran-cu-du-2.3.1.tgz
    version: 2.3.1
  tuned:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-01-04T02:52:32.114413586Z"
    description: Custom srsran-tuned chart packaged by Brandon B. Jozsa
    digest: 8a9ce15b770a282c1937834dfd8a223ba4717fd5266efd5340294624532805e9
    name: tuned
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-tuned/tuned-0.5.0.tgz
    version: 0.5.0
  vms-on-ocpv:
  - apiVersion: v2
    appVersion: v0.1.1-ff18cb3
    created: "2026-01-04T02:52:32.11493459Z"
    description: Simple OpenShift Virtualization chart, typically used for kubevirt-redfish
      testing
    digest: 692e9fad3511c427846065abb355c1d74ed2cae78457feae41692c43cf8d5781
    home: https://github.com/v1k0d3n/vms-on-ocpv
    keywords:
    - kubevirt
    - virtualization
    - vm
    - openshift
    maintainers:
    - email: v1k0d3n@example.com
      name: v1k0d3n
    name: vms-on-ocpv
    sources:
    - https://github.com/v1k0d3n/vms-on-ocpv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/vms-on-ocpv/vms-on-ocpv-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: v0.1.0-ff18cb3
    created: "2026-01-04T02:52:32.114675538Z"
    description: Simple OpenShift Virtualization chart, typically used for kubevirt-redfish
      testing
    digest: ffa58bbbb5c0bed7cc7d92337035c1f0bdeb6d5d8a9e3cdfa9207edd44609bf2
    home: https://github.com/v1k0d3n/vms-on-ocpv
    keywords:
    - kubevirt
    - virtualization
    - vm
    - openshift
    maintainers:
    - email: v1k0d3n@example.com
      name: v1k0d3n
    name: vms-on-ocpv
    sources:
    - https://github.com/v1k0d3n/vms-on-ocpv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/vms-on-ocpv/vms-on-ocpv-0.1.0.tgz
    version: 0.1.0
generated: "2026-01-04T02:52:32.095129554Z"
